### ISSUE TITLE
org.scalatestplus.junit.JUnitSuite cannot be found

### ISSUE THREAD

**Issue by jlprat** [scalatest/scalatest#1553]
As `org.scalatest.junit.JUnitSuite` is deprecated in favor (in theory) of `org.scalatestplus.junit.JUnitSuite` but doesn't seem to be accessible. 

I discovered it while I was trying to upgrade a project to ScalaTest 3.0.7, but it looks like the import `import org.scalatestplus.junit.JUnitSuite` doesn't work anymore (it worked in 3.0.6).
```
[error] /home/jlprat/playground/akka-http/akka-http-core/src/test/java/akka/http/javadsl/model/EntityDiscardingTest.java:15:1: cannot find symbol
[error]   symbol:   class JUnitSuite
[error]   location: package org.scalatestplus.junit
[error] import org.scalatestplus.junit.JUnitSuite;
```

**Comment by cheeseng** [comment]
@jlprat bummer, it seems like our type alias approach for classes in the new package does not work for java source, I'll discuss with @bvenners to see if we shall duplicate the code in the new package instead.

Thanks for reporting, and we apologize for the problem caused.

**Comment by jlprat** [comment]
Sure thing!
It didn't cause any big disruption, no worries.

**Comment by cheeseng** [comment]
@jlprat fyi I released 3.0.8-RC1, do you mind to try it to see if it fixes this issue?

Thanks.

**Comment by jlprat** [comment]
It works with RC1 :+1: 
Thanks a lot!!

**Comment by jlprat** [comment]
For reference: https://github.com/akka/akka-http/pull/2477

**Comment by jlprat** [comment]
Not that there is a big hurry on it, but is three any E.T.A. for 3.0.8 release?

**Comment by cheeseng** [comment]
@jlprat just for your fyi 3.0.8 is now released.

**Comment by jlprat** [comment]
Thank you very much @cheeseng
I already created a PR using the new types and it works on CI.
Feel free to close the ticket, or I can do it myself if you prefer.

**Comment by cheeseng** [comment]
Thank you @jlprat , closing this now.
