### ISSUE TITLE
Publish for Scala 2.13.0-M4?

### ISSUE THREAD

**Issue by SethTisue** [scalatest/scalatest#1367]
M4 JARs are on Maven Central now.

This will probably be more work than the usual upgrades since code will need to be adapted to the new collections. Some advice on that:

* dropping Scala 2.10 support will help
* https://github.com/scala/collection-strawman/wiki/FAQ is your bible
* consider using scala-collection-compat (though a great deal of collections-using code will still cross-compile without it)
* ask questions (so we can help, and to help us improve the FAQ, too)

**Comment by SethTisue** [comment]
P.S. perhaps there are some happy ScalaTest users out there who would like to help.

**Comment by SethTisue** [comment]
upstream ScalaCheck ticket is https://github.com/rickynils/scalacheck/issues/410

**Comment by bvenners** [comment]
@sethtisue we'll get started on it.

**Comment by cheeseng** [comment]
@SethTisue First attempt didn't make it, seems like scalacheck is not there yet, i am curious the reason behind scala-xml version for scala 2.13.0-M4: 

"org.scala-lang.modules" %% "scala-xml_2.13.0-M4-pre-20d3c21" % "1.1.0-newCollectionsBootstrap"

For now I think we'll have to special handle it in our build.

**Comment by SethTisue** [comment]
> , i am curious the reason behind scala-xml version for scala 2.13.0-M4:
> 
> "org.scala-lang.modules" %% "scala-xml_2.13.0-M4-pre-20d3c21" % "1.1.0-newCollectionsBootstrap"

Oh, you'll need to wait until a proper scala-xml has been published for M4. Ticket is https://github.com/scala/scala-xml/issues/217, I should have given you that earlier.

**Comment by cheeseng** [comment]
Thanks @SethTisue , seems like we need some patience here. :)

**Comment by SethTisue** [comment]
scala-xml 1.1.0 is now published for 2.13.0-M4

**Comment by raboof** [comment]
Upstream scalacheck issue: https://github.com/rickynils/scalacheck/issues/410

**Comment by cheeseng** [comment]
@SethTisue Any idea scala-parallel-collections will be published for M4?

**Comment by cheeseng** [comment]
I am trying to get started with fixing for M4, by building the scalacheck locally, here's first batch of M4 related error: 

```
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Chain.scala:1421: type Col takes type parameters
[error]   final def to[Col[_]](implicit cbf: CanBuildFrom[Nothing, T, Col[T @uV]]): Col[T @uV] = toList.to[Col](cbf)
[error]                                                                                                    ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Chain.scala:1518: value toTraversable is not a member of List[T]
[error]   final def toTraversable: Traversable[T] = toList.toTraversable
[error]                                                    ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Chain.scala:1578: type mismatch;
[error]  found   : collection.generic.CanBuildFrom[List[T],U,List[U]]
[error]     (which expands to)  scala.collection.BuildFrom[List[T],U,List[U]]
[error]  required: Int
[error]   final def union[U >: T](that: GenSeq[U])(implicit cbf: CanBuildFrom[List[T], U, List[U]]): Chain[U] = new Chain(toList.union(that)(cbf))
[error]                                                                                                                                      ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/DefaultEquality.scala:38: value deep is not a member of Array[_]
[error]           case brr: Array[_] => arr.deep == brr.deep
[error]                                     ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/DefaultEquality.scala:38: value deep is not a member of Array[_]
[error]           case brr: Array[_] => arr.deep == brr.deep
[error]                                                 ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/DefaultEquality.scala:39: value deep is not a member of Array[_]
[error]           case _ => arr.deep == b
[error]                         ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/DefaultEquality.scala:43: value deep is not a member of Array[_]
[error]           case brr: Array[_] => a == brr.deep
[error]                                          ^
[info] Done updating.
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Every.scala:542: type mismatch;
[error]  found   : scala.collection.MapView[K,org.scalactic.Every[T]]
[error]  required: Map[K,org.scalactic.Every[T]]
[error]     mapKToVec.mapValues { vec => Every(vec.head, vec.tail: _*) }
[error]                         ^
[info] Updating {file:/home/cheeseng/git/scalatest/}scalatestApp...
[info] Resolving org.scalacheck#scalacheck_2.13.0-M4;1.14.1-local-SNAPSHOT ...
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Every.scala:1273: type Col takes type parameters
[error]   final def to[Col[_]](implicit cbf: CanBuildFrom[Nothing, T, Col[T @uV]]): Col[T @uV] = underlying.to[Col](cbf)
[error]                                                                                                        ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Every.scala:1362: value toTraversable is not a member of Vector[T]
[error]   final def toTraversable: Traversable[T] = underlying.toTraversable
[error]                                                        ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Every.scala:1404: type mismatch;
[error]  found   : collection.generic.CanBuildFrom[Vector[T],U,Vector[U]]
[error]     (which expands to)  scala.collection.BuildFrom[Vector[T],U,Vector[U]]
[error]  required: Int
[error]   final def union[U >: T](that: GenSeq[U])(implicit cbf: CanBuildFrom[Vector[T], U, Vector[U]]): Every[U] = fromNonEmptyVector(underlying.union(that)(cbf))
[error]                                                                                                                                                       ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Every.scala:1509: type mismatch;
[error]  found   : Seq[T] (in scala.collection) 
[error]  required: Seq[T] (in scala.collection.immutable) 
[error]           case Some(second) => Some(Many(first, second, seq.tail.tail.seq: _*)) 
[error]                                                                       ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Prettifier.scala:21: object xml is not a member of package scala
[error] import scala.xml
[error]        ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Prettifier.scala:201: type ArrayOps is not a member of package scala.collection.mutable
[error]             case anArrayOps: mutable.ArrayOps[_] => "Array(" + (anArrayOps map apply).mkString(", ") + ")"
[error]                                      ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Prettifier.scala:201: value map is not a member of Any
[error]             case anArrayOps: mutable.ArrayOps[_] => "Array(" + (anArrayOps map apply).mkString(", ") + ")"
[error]                                                                            ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Prettifier.scala:201: missing argument list for method apply
[error] Unapplied methods are only converted to functions when a function type is expected.
[error] You can make this conversion explicit by writing `apply _` or `apply(_)` instead of `apply`.
[error]             case anArrayOps: mutable.ArrayOps[_] => "Array(" + (anArrayOps map apply).mkString(", ") + ")"
[error]                                                                                ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Prettifier.scala:208: not found: value xml
[error]             case anXMLNodeSeq: xml.NodeSeq => anXMLNodeSeq.toString
[error]                                ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Prettifier.scala:209: not found: value xml
[error]             case anXMLNodeBuffer: xml.NodeBuffer =>
[error]                                   ^
[error] /home/cheeseng/git/scalatest/scalactic/src/main/scala/org/scalactic/Prettifier.scala:210: not found: value xml
[error]               xml.NodeSeq.fromSeq(anXMLNodeBuffer).toString
[error]               ^
[error] 19 errors found
```
I am studying https://github.com/scala/collection-strawman/wiki/FAQ to determine what's the best fix for them.

**Comment by lrytz** [comment]
> Any idea scala-parallel-collections will be published for M4?

This will take a while longer, it might only be ready after M5. @szeiger is coordinating this work.

scalacheck 1.14.0 for M4 is now released.

**Comment by cheeseng** [comment]
FYI We're making progress on both 3.0.x and 3.1.x in the following 2 experimental branches: 

https://github.com/cheeseng/scalatest/tree/3.0-scala-2.13.0-M4

https://github.com/cheeseng/scalatest/tree/3.1-scala-2.13.0-M4

After discussion with Bill this morning I think we're going with 3.0.x, will further push it this week so that we can release a version for M4 this week.

@lrytz parallel-collection will be nice to have, we depends on it only in our test, not main, should I think it should not block us from releasing for M4 (will be nice if we can run our test though!).

Thanks!

**Comment by bvenners** [comment]
FYI we decided last night to code generate AnyVal classes in Scalactic that have the collection API so that we can support 2.13 and earlier releases in the same codebase.

**Comment by SethTisue** [comment]
> @lrytz parallel-collection will be nice to have, we depends on it only in our test, not main, should I think it should not block us from releasing for M4 (will be nice if we can run our test though!).

perhaps you could use a Scala-version-specific source directory to swap in a custom `CompatParColls.scala` on 2.13 where `.par` is just the identity function. I didn't look at every single parallel collection test you have, but I looked through a bunch of them and didn't see any that I think wouldn't pass with that pattern. worth considering?

**Comment by cheeseng** [comment]
Sorry for the delay, we just released 3.0.6-SNAP1 that includes build for Scala 2.13.0-M4.

**Comment by xerial** [comment]
@cheeseng Thanks! This version 3.0.6-SNAP1 worked for me.

**Comment by nbauernfeind** [comment]
I cannot figure out why I can't get scalatest to work with scala 2.13.0-M4. When I run tests through sbt I get the following errors:
```
[error] could not find implicit value for parameter pos: org.scalactic.source.Position
[error]   behavior of "DefaultScalaModule"
```

and

```
[error] value should is not a member of String
[error]     result should be ("""{"intValue":1,"stringValue":"foo"}""")
```

IntelliJ seems to figure out that `should` is implicit. I have no idea why it can't figure out the implicit parameter in `behavior of`. Everything compiles correctly for scala 2.12.6. I tried both sbt 1.2.0-M1 and 1.1.6 (hoping than an upgrade from 0.13.7 was the cause).

Any ideas what I've done wrong?

**Comment by nbauernfeind** [comment]
Ah! Looks like those errors popup when I use JDK10. Works fine on JDK8.

**Comment by cheeseng** [comment]
Continue to try to get our tests to build, @SethTisue I did the trick you mentioned above, it does seem to work so far, but it now hit this similar compiler crashed we saw in 2.12.5 (if I remember the error message correctly): 

```
scala.reflect.internal.FatalError: 
  Something is wrong: cannot find T in applied type org.scalatest.matchers.MatcherFactory1[Any,org.scalactic.Equality]
   sought  T in MatcherFactory1
 classSym  MatcherFactory1 in matchers
  tparams  SC in MatcherFactory1, TC1 in MatcherFactory1

     while compiling: /home/cheeseng/git/scalatest/scalatest-test/src/test/scala/org/scalatest/ListShouldBeEmptyLogicalAndSpec.scala
        during phase: typer
     library version: version 2.13.0-M4
    compiler version: version 2.13.0-M4
  reconstructed args: 
```

I think it was fixed in 2.12.6, not sure if the fix is in 2.13 branch?

**Comment by SethTisue** [comment]
@retronym is this https://github.com/scala/bug/issues/10762 ? can you help Chee Seng here?

**Comment by retronym** [comment]
Yep, looks the same. I'm taking a fresh look at the root problem now.

**Comment by retronym** [comment]
I've found the root cause of the regression. We should have a fix for 2.13.0-M5.

In the interim, you could compile with `-Xsource:2.12`, which disables the change in type inference that leads to the problem. Alternatively, or additionally, you could add explicit type annotations to public API in `scalatest/src/main/scala/org/scalatest/matchers/Matcher.scala` and the like.

**Comment by cheeseng** [comment]
@retronym Great thanks @retronym , I'll give -Xsource:2:12 a shot to see if we can build our test.

Thanks!
