### ISSUE TITLE
Can't compile WordSpec when dotty safe initialization check enabled

### ISSUE THREAD

**Issue by HenryS1** [scalatest/scalatest#1970]
I have a dotty project on Scala version `3.0.0-M3` using Scalatest version `3.2.3`. It's been working fine until I enabled the safe initialization check (`-Ycheck-init`) compiler option. Now I can't compile any word specs. I'm able to compile fun suite style specs, but I prefer word spec style. Here's a minimal example that fails to compile
```
package example

import org.scalatest.wordspec._
import org.scalatest.matchers.should.Matchers

class ExampleSpec extends Matchers with AnyWordSpecLike {
  "Example" must {
    "compare 1 to 1" in {
      1 should equal(1)
    }
  }
}
```

And here's the compiler error that I get
```
[error] [E1] src/test/scala/ExampleSpec.scala
[error]      Promoting the value to fully-initialized is unsafe.
[error]       Calling trace:
[error]       -> "compare 1 to 1" in {	[ ExampleSpec.scala:9 ]
[error]      
[error]      The unsafe promotion may cause the following problem(s):
[error]      
[error]      1. Promoting the value under initialization to fully-initialized. Calling trace:
[error]       -> 1 should equal(1)	[ ExampleSpec.scala:10 ]
[error]      
[error]      L9:     "compare 1 to 1" in {
[error]              ^
[error] [E2] src/test/scala/ExampleSpec.scala
[error]      Promoting the value under initialization to fully-initialized. Calling trace:
[error]       -> }	[ ExampleSpec.scala:13 ]
[error]      
[error]      L13:   }
[error]              ^
[error] src/test/scala/ExampleSpec.scala: L9 [E1], L13 [E2]
[info] Legend: Ln = line n, Cn = column n, En = error n
[error] src/test/scala/ExampleSpec.scala: L9 [E1], L13 [E2]
[info] Legend: Ln = line n, Cn = column n, En = error n
[error] (Test / compileIncremental) Compilation failed
[error] Total time: 2 s, completed 22 Feb 2021, 15:55:17
```

**Comment by cheeseng** [comment]
@HenryS1 Sorry for replying so late, I just tested this using -Ysafe-init using our 3.2.x-new branch that builds with scala 3.1.3, it seems like the problem cannot be reproduced anymore.  It seems like the problem is now fixed in scala 3 itself?

**Comment by HenryS1** [comment]
@cheeseng Thanks for following up. I had some other problems with the safe initialisation check at the same time as I hit this compilation error in scalatest so I disabled it. If you've managed to successfully compile this example then it seems that the problem is resolved so I'll close the issue.
