### PR TITLE
fix compilation error if Repeated is included in Diagrams assertion

### PR DESCRIPTION
**Pull request by taisukeoe**
I'd like to report a bug with the latest combination, Scala 3.0.0, ScalaTest 3.2.9 and sbt 1.5.2, and fix the bug by this PR.

# About the bug:
`Test/compile` fails  in Diagrams `assert` which takes an expression including varargs in Scala 3.0.0. It compiles in Scala 2.13.6.

```
[error] -- [E007] Type Mismatch Error: /home/taisukeoe/workspace/Sandbox/scala3-scalatest/src/test/scala/DiagramTest.scala:7:4 
[error] 7 |    assert(Seq("a", "b") == Seq("a"))
[error]   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |    Found:    String*
[error]   |    Required: String
[error]   |
[error]   |    The following import might make progress towards fixing the problem:
[error]   |
[error]   |      import org.scalactic.Prettifier.default
[error]   |
[error]   | This location contains code that was inlined from DiagramTest.scala:9
[error] -- [E007] Type Mismatch Error: /home/taisukeoe/workspace/Sandbox/scala3-scalatest/src/test/scala/DiagramTest.scala:7:4 
[error] 7 |    assert(Seq("a", "b") == Seq("a"))
[error]   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |    Found:    (11 : Int)
[error]   |    Required: String
[error]   |
[error]   |    The following import might make progress towards fixing the problem:
[error]   |
[error]   |      import org.scalactic.Prettifier.default
[error]   |
[error]   | This location contains code that was inlined from DiagramTest.scala:9
```

## Minimal Reproducible project

https://github.com/taisukeoe/scala3-scalatest/tree/aba74a99d00cd42b1215147f62d094a2ce628488

# About This PR

This PR fixes the above compilation error, and make Diagrams assertion works with varargs, which is represented by `Typed(Repeated(_, _), _)` term.

# Note
There is still a Diagrams assertion error message corruption in Scala 3.0.0, as follows.

```
[info]   org.scalatest.diagrams.Diagrams.assert(Seq(a, b) != Seq(3, 5))
[info]                                        | |   |  |  || |   |  |
[info]                                        | |   3  5  || |   3  5
[info]                                        | |         || scala.collection.immutable.Seq$@2c58b1c9
[info]                                        | |         |List(3, 5)
[info]                                        | |         false
[info]                                        | scala.collection.immutable.Seq$@2c58b1c9
[info]                                        List(3, 5) (DirectDiagrammedAssertionsSpec.scala:527)
```

### CODE REVIEW

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@taisukeoe Sorry for getting back late to this and thanks for the fix!  The fix looks good and worked great for Scala 3, but the added test for vararg seems working only under Scala 3, when built with Scala 2: 

```
[error] /home/cheeseng/git/scalatest/jvm/diagrams-test/src/test/scala/org/scalatest/diagrams/DirectDiagrammedAssertionsSpec.scala:601:47: exception during macro expansion: 
[error] scala.MatchError: varargs (of class scala.reflect.internal.Trees$Ident)
[error] 	at org.scalatest.diagrams.DiagrammedExprMacro.traverseApply(DiagrammedExprMacro.scala:110)
[error] 	at org.scalatest.diagrams.DiagrammedExprMacro.applyExpr(DiagrammedExprMacro.scala:202)
[error] 	at org.scalatest.diagrams.DiagrammedExprMacro.transformAst(DiagrammedExprMacro.scala:387)
[error] 	at org.scalatest.diagrams.DiagrammedExprMacro.applyExpr(DiagrammedExprMacro.scala:205)
[error] 	at org.scalatest.diagrams.DiagrammedExprMacro.transformAst(DiagrammedExprMacro.scala:387)
[error] 	at org.scalatest.diagrams.DiagrammedExprMacro.genMacro(DiagrammedExprMacro.scala:421)
[error] 	at org.scalatest.diagrams.DiagramsMacro$.macroImpl(DiagramsMacro.scala:101)
[error] 	at org.scalatest.diagrams.DiagramsMacro$.assert(DiagramsMacro.scala:125)
[error] 	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$6(JavaReflectionRuntimes.scala:51)
[error] 	at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:770)
[error]         org.scalatest.diagrams.Diagrams.assert(varargs(1, "y", "z") == 1 -> Seq("y", "z"))
[error]                                               ^
```

From the error message may be we can enhance our Scala 2 macro to support it, if not perhaps the test can be added under dotty/diagrams-test instead?

**Comment by taisukeoe** [comment]
@cheeseng 
Thank you for confirmation!

> From the error message may be we can enhance our Scala 2 macro to support it, if not perhaps the test can be added under dotty/diagrams-test instead?

As long as I quickly checked, this error is occurred only when `varargs` is defined as local method inside of `describe` method, and there seems to be a rare case if a method needs to be defined inside of `describe`.
So I'd move from `varargs` method to outside of `describe`, because it's nicer not to have Scala 3 specific test file if possible.

**Comment by taisukeoe** [comment]
> Oops, this change seems to break Scala 3 side test. I'm checking this.

It is fixed now. Would you please review this again? @cheeseng

**Comment by cheeseng** [comment]
@taisukeoe Thanks for the latest version!  The changes works great!  One last thing you may want to add the tests into DiagrammedAssertionsSpec.scala also, which is a sibling tests for DiagrammedAssertions that calls the assert function through mixed in trait, instead of directly through Diagrams companion object.

@bvenners I have tested this with Scala 2.10, 2.13, 3.0, js and native.

**Comment by taisukeoe** [comment]
@cheeseng 
Thank you for confirmation. I have added tests to DiagramsSpec as well.
