### ISSUE TITLE
Scala 2.12.0-M5 build for 2.2.x?

### ISSUE THREAD

**Issue by seratch** [scalatest/scalatest#925]
We're stuck with enabling CI with Scala 2.12.0-M5 because of ScalaTest 2.2.6 absence (we have some compilation errors with ScalaTest 3.0). Would you please consider publishing 2.12.0-M5 build for 2.x too?

see also: https://github.com/xuwei-k/scalikejdbc/commit/ceb8e1abce064f4016602ed51b3863d7d2c11793

**Comment by bvenners** [comment]
Sorry, just saw this. We can do a 2.2.6 build early this week.

Meanwhile, can you elaborate on the compiler errors you are seeing with 3.0?

**Comment by seratch** [comment]
The absence of `OneArgTest` brings a compilation error.

```
[error] ~/scalikejdbc-test/src/main/scala/scalikejdbc/scalatest/AutoRollback.scala:51: not found: type OneArgTest
[error]   override def withFixture(test: OneArgTest) = {
[error]                                  ^
[error] one error found
```

Currently, we're publishing builds for Scala 2.10, 2.11 and 2.12.0-M5 with no breaking changes. In the long run, it will be OK to support only ScalaTest 3.x since next major version.

**Comment by bvenners** [comment]
OK, that is one of our breaking changes. What you'll need to do to upgrade this file:

https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-test/src/main/scala/scalikejdbc/scalatest/AutoRollback.scala

is change line 3 from:

    import org.scalatest.fixture.Suite

to:

    import org.scalatest.fixture.TestSuite

And line 31 from:

    trait AutoRollback extends LoanPattern { self: Suite =>

to:

    trait AutoRollback extends LoanPattern { self: TestSuite =>

I.e., just put "Test" in front of "Suite" in those two places. We had to introduce `TestSuite` and move `withFixture` down to it because the signature of `withFixture` didn't work for the new async styles.

**Comment by seratch** [comment]
Thank you for the response about ScalaTest 3.0 changes. BTW, would you please work on the 2.2.6 release for Scala 2.12.0-M5 when you have time?
