### PR TITLE
[3.0] Scala 2.13.0-M5 Support

### PR DESCRIPTION
**Pull request by cheeseng**
Getting 3.0.x to build with Scala 2.13.0-M5.

### CODE REVIEW

**Comment by bvenners** [comment]
@cheeseng Travis failed with several attempts to find an XML library:

```
[error] /home/travis/build/scalatest/scalatest/scalactic-macro/target/scala-2.13.0-M2/src_managed/main/org/scalatest/ColCompatHelper.scala:20: type IndexedSeqOps is not a member of package collection
[error]   type IndexedSeqLike[+A, +Repr] = scala.collection.IndexedSeqOps[A, IndexedSeq, Repr]
[error]                                                     ^
[error] one error found
sbt.ResolveException: unresolved dependency: org.scala-lang.modules#scala-xml_2.13.0-M2;1.1.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
```

Is that because ths is not yet ready for M5?

**Comment by ashawley** [comment]
There is a scala-xml 1.1.0 published for 2.13.0-M5.  Looks like `.travis.yml` just needs to be updated:  It references `2.13.0-M2`.

**Comment by bvenners** [comment]
@ashawley Thanks. We'll try that.

**Comment by cheeseng** [comment]
@bvenners I pushed a commit to take out the travis build for 2.13, because it is expected to fail anyway due to the behavior difference of the collection's string representation method.

**Comment by lloydmeta** [comment]
> @bvenners I pushed a commit to take out the travis build for 2.13, because it is expected to fail anyway due to the behavior difference of the collection's string representation method.

I'm running into an issue with this under ScalaJS and 2.13.0-M5, but not quite sure how to proceed? https://github.com/lloydmeta/enumeratum/pull/202#issuecomment-431643804

Should I file a bug ? Or is this to be expected ?
