### ISSUE TITLE
HtmlUnitDriver not found

### ISSUE THREAD

**Issue by thebridsk** [scalatest/scalatest#1561]
Using scalatest 3.0.7 and selenium-java 3.141.59 

Small repo that shows the problem: https://github.com/thebridsk/bugScalatestSelenium
- **master** branch shows the HtmlUnitDriver error
- **v3.0.6** branch show it working with scalatest 3.0.6
- **htmlunit** branch shows the Firefox error, htmlunit-driver in classpath

For testing, I'm using chromedriver, not htmlunitdriver.  I don't mention htmlunitdriver in my code.  The same code works with scalatest 3.0.6

I'm including
   selenium-java 3.141.59 in the runtime

Maybe the org/scalatestplus/package.scala should use `lazy val` instead of `val` to bring in all the objects from org.scalatest... 

 java.lang.NoClassDefFoundError: org.openqa.selenium.htmlunit.HtmlUnitDriver
  at org.scalatest.selenium.HtmlUnit.$init$(WebBrowser.scala:4480)
  at org.scalatest.selenium.HtmlUnit$.<init>(WebBrowser.scala:4498)
  at org.scalatest.selenium.HtmlUnit$.<clinit>(WebBrowser.scala)
  at org.scalatestplus.selenium.package$.<init>(package.scala:71)
  at org.scalatestplus.selenium.package$.<clinit>(package.scala)

When I include  
   "org.seleniumhq.selenium" % "htmlunit-driver" % "2.34.0" 

I get past the above error and hit this error:

  java.lang.NoSuchMethodError: org/openqa/selenium/firefox/FirefoxDriver.<init>(Lorg/openqa/selenium/firefox/FirefoxProfile;)V (loaded from file:/C:/Users/xxx/.ivy2/cache/org.seleniumhq.selenium/selenium-firefox-driver/jars/selenium-firefox-driver-3.141.59.jar by java.net.URLClassLoader@b5523ac3) called from interface org.scalatest.selenium.Firefox (loaded from file:/C:/Users/xxx/.ivy2/cache/org.scalatest/scalatest_2.12/jars/scalatest_2.12-3.0.7.jar by java.net.URLClassLoader@b5523ac3).
  at org.scalatest.selenium.Firefox.$init$(WebBrowser.scala:4530)
  at org.scalatest.selenium.Firefox$.<init>(WebBrowser.scala:4546)
  at org.scalatest.selenium.Firefox$.<clinit>(WebBrowser.scala)
  at org.scalatestplus.selenium.package$.<init>(package.scala:75)
  at org.scalatestplus.selenium.package$.<clinit>(package.scala)
  at com.example.test.util.SeleniumUtils.findButtonAndClick(SeleniumUtils.scala:337)
  at com.example.test.util.SeleniumUtils.findButtonAndClick$(SeleniumUtils.scala:333)
  at com.example.test.selenium.RubberTest.findButtonAndClick(RubberTest.scala:46)
  at com.example.test.selenium.RubberTest.$anonfun$new$3(RubberTest.scala:166)
  at com.example.test.selenium.RubberTest$$Lambda$476.0000000011D1DEF0.apply$mcV$sp(Unknown Source)
  ...

**Comment by thebridsk** [comment]
No longer a problem in 3.0.8
