### ISSUE TITLE
java.lang.NoSuchMethodError: org.scalactic.BooleanMacro when upgrading scalactic from 3.0.x to 3.1.x

### ISSUE THREAD

**Issue by codan84** [scalatest/scalatest#1934]
Tests compile/run fine with scalactic 3.0.x but fail compilation when upgrading to 3.1.x with this error:
```
[error] java.lang.NoSuchMethodError: org.scalactic.BooleanMacro.<init>(Lscala/reflect/macros/whitebox/Context;Ljava/lang/String;)V
[error] 	at org.scalatest.AssertionsMacro$.assert(AssertionsMacro.scala:34)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$6(JavaReflectionRuntimes.scala:51)
[error] 	at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:824)
[error] 	at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime$(Macros.scala:800)
[error] 	at splain.SplainPlugin$$anon$1.macroExpandWithRuntime(SplainPlugin.scala:10)
[error] 	at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:630)
[error] 	at scala.tools.nsc.Global.withInfoLevel(Global.scala:228)
[error] 	at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:623)
[error] 	at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:610)
[error] 	at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:785)
[error] 	at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:783)
[error] 	at splain.SplainPlugin$$anon$1.standardMacroExpand(SplainPlugin.scala:10)
[error] 	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:457)
[error] 	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:454)
[error] 	at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:411)
[error] 	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:454)
[error] 	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:454)
[error] 	at splain.SplainPlugin$$anon$1.pluginsMacroExpand(SplainPlugin.scala:10)
[error] 	at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:774)
[error] 	at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:767)
[error] 	at splain.SplainPlugin$$anon$1.macroExpand(SplainPlugin.scala:10)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1164)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1224)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5730)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$2(Typers.scala:865)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$silent$2(Typers.scala:727)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:727)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:862)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:490)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1220)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5730)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2486)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$102(Typers.scala:5645)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:499)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5680)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5716)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3371)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:490)
[error] 	at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgWithFormal$1(PatternTypers.scala:113)
[error] 	at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.$anonfun$typedArgsForFormals$4(PatternTypers.scala:129)
[error] 	at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals(PatternTypers.scala:129)
[error] 	at scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals$(PatternTypers.scala:110)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedArgsForFormals(Typers.scala:201)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3710)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3743)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$26(Typers.scala:4772)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:714)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:4772)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4856)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4867)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5670)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5716)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5780)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3353)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3353)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2013)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1826)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5636)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5716)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5780)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3353)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3353)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5346)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5639)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5716)
[error] 	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:114)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:453)
[error] 	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:103)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1503)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1480)
[error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1606)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1761)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1734)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (common / Test / compileIncremental) java.lang.NoSuchMethodError: org.scalactic.BooleanMacro.<init>(Lscala/reflect/macros/whitebox/Context;Ljava/lang/String;)V
```
Any clue what could cause this issue? Can't seem to nail down what got removed that I am using. There are no other warnings etc. I checked changelog for 3.1.0 and nothing stands out for me.

**Comment by kastoestoramadus** [comment]
try with those answers:
https://stackoverflow.com/questions/39812037/error-on-scalatest-compilation-in-idea
