### ISSUE TITLE
Regression in 3.1.0-SNAP8

### ISSUE THREAD

**Issue by erikvanoosten** [scalatest/scalatest#1548]
After upgrading to 3.1.0-SNAP8 my builds fail (it is the only change) for all JVM targets: https://travis-ci.org/erikvanoosten/metrics-scala/builds/505755504

The error is:

```
[error] /home/travis/build/erikvanoosten/metrics-scala/metrics-scala/src/test/scala/nl/grons/metrics4/scala/CheckedBuilderSpec.scala:27:22: object mockito is not a member of package org.scalatest
[error] import org.scalatest.mockito.MockitoSugar._
[error]                      ^
```

**Comment by cheeseng** [comment]
Hi @erikvanoosten , the reason is that's part of our modularization effort in 3.1.x that was just merged yesterday: 

https://github.com/scalatest/scalatest/pull/1546

We have been deprecated org.scalatest.mockito.MockitoSugar and moved it to org.scalatestplus.mockito.MockitoSugar in 3.0.6/3.0.7: 

https://github.com/scalatest/scalatest/releases/tag/release-3.0.6

Since you're using 3.1.0-SNAP8, you can add the following dependency to your build: 

```
"org.scalatestplus" %% "scalatestplus-mockito" % "1.0.0-SNAP1"
```

in order to rename org.scalatest.mockito to org.scalatestplus.mockito, you can also try our autofix tool: 

https://github.com/scalatest/autofix/tree/master/3.0.6

Hope this helps.

**Comment by erikvanoosten** [comment]
Thanks a lot!
Makes sense to shed some load now that Mockito has its own scala API.
